version: '3.1'

services:
  db_docker:
    image: postgres
    container_name: db_docker
    hostname: db_docker
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_DB: api_db

  test_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test_api
    hostname: test_api
    image: test_api
    environment:
      POSTGRES_HOST: db_docker
      POSTGRES_PASSWORD: test
      POSTGRES_USER: postgres
      POSTGRES_DB: api_db
      POSTGRES_PORT: 5432
      FAKE_DB: 1
    ports:
      - 5000:5000
    restart: on-failure
    depends_on:
      - db_docker

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080